spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://localhost:5432/oth_nest_db

#server authentication credentials
spring.datasource.username=postgres
spring.datasource.password=801410

#control table syncing strategies (automatically creates/updates columns)
spring.jpa.hibernate.ddl-auto=update

#not execute data.sql
#spring.sql.init.mode=never

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=false